// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

/** @deprecated */
@available(*, deprecated)
final class DeprecatedInterfaceCppProxy: DjinniSupport.CppProxy, TestSuite.DeprecatedInterface {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
    func foo() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.DeprecatedInterface_foo(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    func bar() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.DeprecatedInterface_bar(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
}
let deprecatedInterfaceMethods: Vtbl<DeprecatedInterface> = [
    { inst, params, ret in
        djinni.swift.setReturnValue(ret, try I32Marshaller.toCpp(inst.foo()))
    },
    { inst, params, ret in
        djinni.swift.setReturnValue(ret, try I32Marshaller.toCpp(inst.bar()))
    },
]

public enum DeprecatedInterfaceMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.DeprecatedInterface
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { DeprecatedInterfaceCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { djinni_generated.DeprecatedInterfaceSwiftProxy.make(ctxPtr(s, deprecatedInterfaceMethods), dispatcherProtocalCall)})
    }
}
