// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import Foundation

/** @deprecated */
@available(*, deprecated)
public protocol DeprecatedInterface: AnyObject {
    /** @deprecated */
    @available(*, deprecated)
    func foo() throws -> Int32
    /** @deprecated This is a deprecation message */
    @available(*, deprecated, message: "This is a deprecation message")
    func bar() throws -> Int32
}
