// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import Foundation

/** @deprecated */
@available(*, deprecated)
public struct DeprecatedRecord {
    public var foo: Int32
    /** @deprecated */
    @available(*, deprecated)
    public var bar: Int32
    /** @deprecated This is a deprecation message */
    @available(*, deprecated, message: "This is a deprecation message")
    public var baz: Int32

    public init(foo: Int32, bar: Int32, baz: Int32)
    {
        self.foo = foo
        self.bar = bar
        self.baz = baz
    }
}
