// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

/** @deprecated This is a deprecation message */
@available(*, deprecated, message: "This is a deprecation message")
final class DeprecatedInterfaceWithStaticCppProxy: DjinniSupport.CppProxy, TestSuite.DeprecatedInterfaceWithStatic {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
}
let deprecatedInterfaceWithStaticMethods: Vtbl<DeprecatedInterfaceWithStatic> = [
]

public enum DeprecatedInterfaceWithStaticMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.DeprecatedInterfaceWithStatic
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { DeprecatedInterfaceWithStaticCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { djinni_generated.DeprecatedInterfaceWithStaticSwiftProxy.make(ctxPtr(s, deprecatedInterfaceWithStaticMethods), dispatcherProtocalCall)})
    }
}
public class DeprecatedInterfaceWithStatic_statics {
    /** @deprecated */
    @available(*, deprecated)
    public static func foo() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.DeprecatedInterfaceWithStatic_foo(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    /** @deprecated This is a deprecation message */
    @available(*, deprecated, message: "This is a deprecation message")
    public static func bar() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        var ret = djinni_generated.DeprecatedInterfaceWithStatic_bar(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
}
