// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import DjinniSupport
import TestSuite

public typealias DeprecatedEnumWithMessageMarshaller = DjinniSupport.EnumMarshaller<DeprecatedEnumWithMessage>
