// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import Foundation

/** @deprecated This is a deprecation message */
@available(*, deprecated, message: "This is a deprecation message")
public protocol DeprecatedInterfaceWithStatic: AnyObject {
}
