// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import DjinniSupport
import TestSuite

public typealias DeprecatedEnumMarshaller = DjinniSupport.EnumMarshaller<DeprecatedEnum>
