// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

/** @deprecated This is a deprecation message */
@available(*, deprecated, message: "This is a deprecation message")
final class DeprecatedInterfaceWithMessageCppProxy: DjinniSupport.CppProxy, TestSuite.DeprecatedInterfaceWithMessage {
    init(_ inst: djinni.swift.AnyValue) { super.init(inst:inst) } 
    func foo() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.DeprecatedInterfaceWithMessage_foo(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
    func bar() throws -> Int32 {
        var _params = djinni.swift.ParameterList()
        _params.addValue(inst)
        var ret = djinni_generated.DeprecatedInterfaceWithMessage_bar(&_params)
        try handleCppErrors(&ret)
        return I32Marshaller.fromCpp(ret)
    }
}
let deprecatedInterfaceWithMessageMethods: Vtbl<DeprecatedInterfaceWithMessage> = [
    { inst, params, ret in
        djinni.swift.setReturnValue(ret, try I32Marshaller.toCpp(inst.foo()))
    },
    { inst, params, ret in
        djinni.swift.setReturnValue(ret, try I32Marshaller.toCpp(inst.bar()))
    },
]

public enum DeprecatedInterfaceWithMessageMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.DeprecatedInterfaceWithMessage
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return cppInterfaceToSwift(c, { DeprecatedInterfaceWithMessageCppProxy(c) as SwiftType })
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        return swiftInterfaceToCpp(s, { djinni_generated.DeprecatedInterfaceWithMessageSwiftProxy.make(ctxPtr(s, deprecatedInterfaceWithMessageMethods), dispatcherProtocalCall)})
    }
}
