// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

import DjinniSupport
import DjinniSupportCxx
import Foundation
import TestSuite
import TestSuiteCxx

public enum DeprecatedRecordMarshaller: DjinniSupport.Marshaller {
    public typealias SwiftType = TestSuite.DeprecatedRecord
    public static func fromCpp(_ c: djinni.swift.AnyValue) -> SwiftType {
        return withUnsafePointer(to: c) { p in
            let foo = I32Marshaller.fromCpp(djinni.swift.getMember(p, 0))
            let bar = I32Marshaller.fromCpp(djinni.swift.getMember(p, 1))
            let baz = I32Marshaller.fromCpp(djinni.swift.getMember(p, 2))
            return SwiftType(foo: foo, bar: bar, baz: baz)
        }
    }
    public static func toCpp(_ s: SwiftType) -> djinni.swift.AnyValue {
        var ret = djinni.swift.makeCompositeValue()
        djinni.swift.addMember(&ret, I32Marshaller.toCpp(s.foo))
        djinni.swift.addMember(&ret, I32Marshaller.toCpp(s.bar))
        djinni.swift.addMember(&ret, I32Marshaller.toCpp(s.baz))
        return ret
    }
}
