// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

/** @deprecated This is a deprecation message */
@available(*, deprecated, message: "This is a deprecation message")
public enum DeprecatedEnumWithMessage: Int32 {
    case foo = 0
    /** @deprecated */
    @available(*, deprecated)
    case bar = 1
    /** @deprecated This is a deprecation message */
    @available(*, deprecated, message: "This is a deprecation message")
    case baz = 2
}
