// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_enum_with_message.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDeprecatedEnumWithMessage final : ::djinni::JniEnum {
public:
    using CppType = ::testsuite::deprecated_enum_with_message;
    using JniType = jobject;

    using Boxed = NativeDeprecatedEnumWithMessage;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeDeprecatedEnumWithMessage>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeDeprecatedEnumWithMessage>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeDeprecatedEnumWithMessage() : JniEnum("com/dropbox/djinni/test/DeprecatedEnumWithMessage") {}
    friend ::djinni::JniClass<NativeDeprecatedEnumWithMessage>;
};

} // namespace djinni_generated
