// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterface.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeDeprecatedInterface::NativeDeprecatedInterface() : ::djinni::JniInterface<::testsuite::DeprecatedInterface, NativeDeprecatedInterface>("com/dropbox/djinni/test/DeprecatedInterface$CppProxy") {}

NativeDeprecatedInterface::~NativeDeprecatedInterface() = default;

NativeDeprecatedInterface::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeDeprecatedInterface::JavaProxy::~JavaProxy() = default;

int32_t NativeDeprecatedInterface::JavaProxy::foo() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeDeprecatedInterface>::get();
    auto jret = jniEnv->CallIntMethod(Handle::get().get(), data.method_foo);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I32::toCpp(jniEnv, jret);
}
int32_t NativeDeprecatedInterface::JavaProxy::bar() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeDeprecatedInterface>::get();
    auto jret = jniEnv->CallIntMethod(Handle::get().get(), data.method_bar);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I32::toCpp(jniEnv, jret);
}

CJNIEXPORT void JNICALL Java_com_dropbox_djinni_test_DeprecatedInterface_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::testsuite::DeprecatedInterface>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_DeprecatedInterface_00024CppProxy_native_1foo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::testsuite::DeprecatedInterface>(nativeRef);
        auto r = ref->foo();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_DeprecatedInterface_00024CppProxy_native_1bar(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::testsuite::DeprecatedInterface>(nativeRef);
        auto r = ref->bar();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
