// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_enum.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDeprecatedEnum final : ::djinni::JniEnum {
public:
    using CppType = ::testsuite::deprecated_enum;
    using JniType = jobject;

    using Boxed = NativeDeprecatedEnum;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeDeprecatedEnum>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeDeprecatedEnum>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeDeprecatedEnum() : JniEnum("com/dropbox/djinni/test/DeprecatedEnum") {}
    friend ::djinni::JniClass<NativeDeprecatedEnum>;
};

} // namespace djinni_generated
