// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_record_with_message.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDeprecatedRecordWithMessage final {
public:
    using CppType = ::testsuite::DeprecatedRecordWithMessage;
    using JniType = jobject;

    using Boxed = NativeDeprecatedRecordWithMessage;

    ~NativeDeprecatedRecordWithMessage();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeDeprecatedRecordWithMessage();
    friend ::djinni::JniClass<NativeDeprecatedRecordWithMessage>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/DeprecatedRecordWithMessage") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(III)V") };
    const jfieldID field_mFoo { ::djinni::jniGetFieldID(clazz.get(), "mFoo", "I") };
    const jfieldID field_mBar { ::djinni::jniGetFieldID(clazz.get(), "mBar", "I") };
    const jfieldID field_mBaz { ::djinni::jniGetFieldID(clazz.get(), "mBaz", "I") };
};

} // namespace djinni_generated
