// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_interface_with_message.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDeprecatedInterfaceWithMessage final : ::djinni::JniInterface<::testsuite::DeprecatedInterfaceWithMessage, NativeDeprecatedInterfaceWithMessage> {
public:
    using CppType = std::shared_ptr<::testsuite::DeprecatedInterfaceWithMessage>;
    using CppOptType = std::shared_ptr<::testsuite::DeprecatedInterfaceWithMessage>;
    using JniType = jobject;

    using Boxed = NativeDeprecatedInterfaceWithMessage;

    ~NativeDeprecatedInterfaceWithMessage();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDeprecatedInterfaceWithMessage>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDeprecatedInterfaceWithMessage>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDeprecatedInterfaceWithMessage();
    friend ::djinni::JniClass<NativeDeprecatedInterfaceWithMessage>;
    friend ::djinni::JniInterface<::testsuite::DeprecatedInterfaceWithMessage, NativeDeprecatedInterfaceWithMessage>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::testsuite::DeprecatedInterfaceWithMessage
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        int32_t foo() override;
        int32_t bar() override;

    private:
        friend ::djinni::JniInterface<::testsuite::DeprecatedInterfaceWithMessage, ::djinni_generated::NativeDeprecatedInterfaceWithMessage>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/DeprecatedInterfaceWithMessage") };
    const jmethodID method_foo { ::djinni::jniGetMethodID(clazz.get(), "foo", "()I") };
    const jmethodID method_bar { ::djinni::jniGetMethodID(clazz.get(), "bar", "()I") };
};

} // namespace djinni_generated
