// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterfaceWithStatic.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeDeprecatedInterfaceWithStatic::NativeDeprecatedInterfaceWithStatic() : ::djinni::JniInterface<::testsuite::DeprecatedInterfaceWithStatic, NativeDeprecatedInterfaceWithStatic>("com/dropbox/djinni/test/DeprecatedInterfaceWithStatic$CppProxy") {}

NativeDeprecatedInterfaceWithStatic::~NativeDeprecatedInterfaceWithStatic() = default;


CJNIEXPORT void JNICALL Java_com_dropbox_djinni_test_DeprecatedInterfaceWithStatic_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::testsuite::DeprecatedInterfaceWithStatic>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_DeprecatedInterfaceWithStatic_foo(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::DeprecatedInterfaceWithStatic::foo();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_dropbox_djinni_test_DeprecatedInterfaceWithStatic_bar(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::testsuite::DeprecatedInterfaceWithStatic::bar();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
