// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDeprecatedRecord final {
public:
    using CppType = ::testsuite::DeprecatedRecord;
    using JniType = jobject;

    using Boxed = NativeDeprecatedRecord;

    ~NativeDeprecatedRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeDeprecatedRecord();
    friend ::djinni::JniClass<NativeDeprecatedRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/DeprecatedRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(III)V") };
    const jfieldID field_mFoo { ::djinni::jniGetFieldID(clazz.get(), "mFoo", "I") };
    const jfieldID field_mBar { ::djinni::jniGetFieldID(clazz.get(), "mBar", "I") };
    const jfieldID field_mBaz { ::djinni::jniGetFieldID(clazz.get(), "mBaz", "I") };
};

} // namespace djinni_generated
