// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

package com.dropbox.djinni.test;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** @deprecated This is a deprecation message */
@Deprecated
public abstract class DeprecatedInterfaceWithStatic {
    /** @deprecated */
    @Deprecated
    public static native int foo();

    /** @deprecated This is a deprecation message */
    @Deprecated
    public static native int bar();

    public static final class CppProxy extends DeprecatedInterfaceWithStatic
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);
    }
}
