// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** @deprecated This is a deprecation message */
@Deprecated
public enum DeprecatedEnumWithMessage {
    FOO,
    /** @deprecated */
    @Deprecated
    BAR,
    /** @deprecated This is a deprecation message */
    @Deprecated
    BAZ,
    ;
}
