// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** @deprecated */
@Deprecated
public class DeprecatedRecord {


    /*package*/ int mFoo;

    /*package*/ int mBar;

    /*package*/ int mBaz;

    public DeprecatedRecord(
            int foo,
            int bar,
            int baz) {
        this.mFoo = foo;
        this.mBar = bar;
        this.mBaz = baz;
    }

    public int getFoo() {
        return mFoo;
    }

    public void setFoo(int foo) {
        this.mFoo = foo;
    }

    /** @deprecated */
    @Deprecated
    public int getBar() {
        return mBar;
    }

    public void setBar(int bar) {
        this.mBar = bar;
    }

    /** @deprecated This is a deprecation message */
    @Deprecated
    public int getBaz() {
        return mBaz;
    }

    public void setBaz(int baz) {
        this.mBaz = baz;
    }

    @Override
    public String toString() {
        return "DeprecatedRecord{" +
                "mFoo=" + mFoo +
                "," + "mBar=" + mBar +
                "," + "mBaz=" + mBaz +
        "}";
    }

}
