// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include <cstdint>

namespace testsuite {

/** @deprecated */
class [[deprecated]] DeprecatedInterface {
public:
    virtual ~DeprecatedInterface() = default;

    /** @deprecated Deprecated constant */
    [[deprecated("Deprecated constant")]]
    static constexpr int32_t BAZ = 0;

    /** @deprecated */
    [[deprecated]]
    virtual int32_t foo() = 0;

    /** @deprecated This is a deprecation message */
    [[deprecated("This is a deprecation message")]]
    virtual int32_t bar() = 0;
};

} // namespace testsuite
