// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include <cstdint>

namespace testsuite {

/** @deprecated This is a deprecation message */
class [[deprecated("This is a deprecation message")]] DeprecatedInterfaceWithStatic {
public:
    virtual ~DeprecatedInterfaceWithStatic() = default;

    /** @deprecated */
    [[deprecated]]
    static int32_t foo();

    /** @deprecated This is a deprecation message */
    [[deprecated("This is a deprecation message")]]
    static int32_t bar();
};

} // namespace testsuite
