// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace testsuite {

/** @deprecated This is a deprecation message */
struct [[deprecated("This is a deprecation message")]] DeprecatedRecordWithMessage final {
    int32_t foo;
    /** @deprecated */
    [[deprecated]]
    int32_t bar;
    /** @deprecated This is a deprecation message */
    [[deprecated("This is a deprecation message")]]
    int32_t baz;

    DeprecatedRecordWithMessage(int32_t foo_,
                                int32_t bar_,
                                int32_t baz_)
    : foo(std::move(foo_))
    , bar(std::move(bar_))
    , baz(std::move(baz_))
    {}
};

} // namespace testsuite
