// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "deprecated_interface_with_message.hpp"  // my header

namespace testsuite {


} // namespace testsuite
