// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include <functional>

namespace testsuite {

/** @deprecated */
enum class [[deprecated]] deprecated_enum : int {
    FOO = 0,
    /** @deprecated */
    BAR [[deprecated]] = 1,
    /** @deprecated This is a deprecation message */
    BAZ [[deprecated("This is a deprecation message")]] = 2,
};

constexpr const char* to_string(deprecated_enum e) noexcept {
    constexpr const char* names[] = {
        "foo",
        "bar",
        "baz",
    };
    return names[static_cast<int>(e)];
}

} // namespace testsuite

namespace std {

template <>
struct hash<::testsuite::deprecated_enum> {
    size_t operator()(::testsuite::deprecated_enum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
