// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedEnum.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_testsuite_deprecated_enum_consts, (), {
        Module.testsuite_DeprecatedEnum =  {
            FOO : 0,
            /** @deprecated */
            BAR : 1,
            /** @deprecated This is a deprecation message */
            BAZ : 2,
        }
    })
}

void NativeDeprecatedEnum::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_testsuite_deprecated_enum_consts();
        ::djinni::djinni_register_name_in_ns("testsuite_DeprecatedEnum", "testsuite.DeprecatedEnum");
    });
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_enum) {
    NativeDeprecatedEnum::staticInitializeConstants();
}

} // namespace djinni_generated
