// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_record_with_message.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeDeprecatedRecordWithMessage
{
    using CppType = ::testsuite::DeprecatedRecordWithMessage;
    using JsType = em::val;
    using Boxed = NativeDeprecatedRecordWithMessage;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
