// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_record.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeDeprecatedRecord
{
    using CppType = ::testsuite::DeprecatedRecord;
    using JsType = em::val;
    using Boxed = NativeDeprecatedRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
