// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedEnumWithMessage.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_testsuite_deprecated_enum_with_message_consts, (), {
        Module.testsuite_DeprecatedEnumWithMessage =  {
            FOO : 0,
            /** @deprecated */
            BAR : 1,
            /** @deprecated This is a deprecation message */
            BAZ : 2,
        }
    })
}

void NativeDeprecatedEnumWithMessage::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_testsuite_deprecated_enum_with_message_consts();
        ::djinni::djinni_register_name_in_ns("testsuite_DeprecatedEnumWithMessage", "testsuite.DeprecatedEnumWithMessage");
    });
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_enum_with_message) {
    NativeDeprecatedEnumWithMessage::staticInitializeConstants();
}

} // namespace djinni_generated
