// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_interface_with_static.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeDeprecatedInterfaceWithStatic : ::djinni::JsInterface<::testsuite::DeprecatedInterfaceWithStatic, NativeDeprecatedInterfaceWithStatic> {
    using CppType = std::shared_ptr<::testsuite::DeprecatedInterfaceWithStatic>;
    using CppOptType = std::shared_ptr<::testsuite::DeprecatedInterfaceWithStatic>;
    using JsType = em::val;
    using Boxed = NativeDeprecatedInterfaceWithStatic;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "NativeDeprecatedInterfaceWithStatic::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static int32_t foo();
    static int32_t bar();

};

} // namespace djinni_generated
