// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterface.hpp"  // my header

namespace djinni_generated {

em::val NativeDeprecatedInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "foo",
        "bar",
    });
    return methods;
}

int32_t NativeDeprecatedInterface::foo(const CppType& self) {
    try {
        auto r = self->foo();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
int32_t NativeDeprecatedInterface::bar(const CppType& self) {
    try {
        auto r = self->bar();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_interface) {
    ::djinni::DjinniClass_<::testsuite::DeprecatedInterface>("testsuite_DeprecatedInterface", "testsuite.DeprecatedInterface")
        .smart_ptr<std::shared_ptr<::testsuite::DeprecatedInterface>>("testsuite_DeprecatedInterface")
        .function("nativeDestroy", &NativeDeprecatedInterface::nativeDestroy)
        .function("foo", NativeDeprecatedInterface::foo)
        .function("bar", NativeDeprecatedInterface::bar)
        ;
}

namespace {
    EM_JS(void, djinni_init_testsuite_deprecated_interface_consts, (), {
        if (!('testsuite_DeprecatedInterface' in Module)) {
            Module.testsuite_DeprecatedInterface = {};
        }
        Module.testsuite_DeprecatedInterface.BAZ = 0;
    })
}
void NativeDeprecatedInterface::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_testsuite_deprecated_interface_consts();
        ::djinni::djinni_register_name_in_ns("testsuite_DeprecatedInterface", "testsuite.DeprecatedInterface");
    });
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_interface_consts) {
    NativeDeprecatedInterface::staticInitializeConstants();
}

} // namespace djinni_generated
