// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_enum_with_message.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeDeprecatedEnumWithMessage: ::djinni::WasmEnum<::testsuite::deprecated_enum_with_message> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
