// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterfaceWithMessage.hpp"  // my header

namespace djinni_generated {

em::val NativeDeprecatedInterfaceWithMessage::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "foo",
        "bar",
    });
    return methods;
}

int32_t NativeDeprecatedInterfaceWithMessage::foo(const CppType& self) {
    try {
        auto r = self->foo();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
int32_t NativeDeprecatedInterfaceWithMessage::bar(const CppType& self) {
    try {
        auto r = self->bar();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_interface_with_message) {
    ::djinni::DjinniClass_<::testsuite::DeprecatedInterfaceWithMessage>("testsuite_DeprecatedInterfaceWithMessage", "testsuite.DeprecatedInterfaceWithMessage")
        .smart_ptr<std::shared_ptr<::testsuite::DeprecatedInterfaceWithMessage>>("testsuite_DeprecatedInterfaceWithMessage")
        .function("nativeDestroy", &NativeDeprecatedInterfaceWithMessage::nativeDestroy)
        .function("foo", NativeDeprecatedInterfaceWithMessage::foo)
        .function("bar", NativeDeprecatedInterfaceWithMessage::bar)
        ;
}

namespace {
    EM_JS(void, djinni_init_testsuite_deprecated_interface_with_message_consts, (), {
        if (!('testsuite_DeprecatedInterfaceWithMessage' in Module)) {
            Module.testsuite_DeprecatedInterfaceWithMessage = {};
        }
        Module.testsuite_DeprecatedInterfaceWithMessage.BAZ = 0;
    })
}
void NativeDeprecatedInterfaceWithMessage::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_testsuite_deprecated_interface_with_message_consts();
        ::djinni::djinni_register_name_in_ns("testsuite_DeprecatedInterfaceWithMessage", "testsuite.DeprecatedInterfaceWithMessage");
    });
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_interface_with_message_consts) {
    NativeDeprecatedInterfaceWithMessage::staticInitializeConstants();
}

} // namespace djinni_generated
