// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterfaceWithStatic.hpp"  // my header

namespace djinni_generated {

em::val NativeDeprecatedInterfaceWithStatic::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

int32_t NativeDeprecatedInterfaceWithStatic::foo() {
    try {
        auto r = ::testsuite::DeprecatedInterfaceWithStatic::foo();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}
int32_t NativeDeprecatedInterfaceWithStatic::bar() {
    try {
        auto r = ::testsuite::DeprecatedInterfaceWithStatic::bar();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(testsuite_deprecated_interface_with_static) {
    ::djinni::DjinniClass_<::testsuite::DeprecatedInterfaceWithStatic>("testsuite_DeprecatedInterfaceWithStatic", "testsuite.DeprecatedInterfaceWithStatic")
        .smart_ptr<std::shared_ptr<::testsuite::DeprecatedInterfaceWithStatic>>("testsuite_DeprecatedInterfaceWithStatic")
        .function("nativeDestroy", &NativeDeprecatedInterfaceWithStatic::nativeDestroy)
        .class_function("foo", NativeDeprecatedInterfaceWithStatic::foo)
        .class_function("bar", NativeDeprecatedInterfaceWithStatic::bar)
        ;
}

} // namespace djinni_generated
