// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_enum.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeDeprecatedEnum: ::djinni::WasmEnum<::testsuite::deprecated_enum> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
