// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterfaceWithStatic.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue DeprecatedInterfaceWithStatic_foo(const djinni::swift::ParameterList* params) try {
    auto ret = ::testsuite::DeprecatedInterfaceWithStatic::foo();
    return ::djinni::swift::I32::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue DeprecatedInterfaceWithStatic_bar(const djinni::swift::ParameterList* params) try {
    auto ret = ::testsuite::DeprecatedInterfaceWithStatic::bar();
    return ::djinni::swift::I32::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue DeprecatedInterfaceWithStaticSwiftProxy::make(void* instance, djinni::swift::DispatchFunc dispatcher) {
    return {std::make_shared<DeprecatedInterfaceWithStaticSwiftProxy>(instance, dispatcher)};
}

} // namespace djinni_generated
