// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterface.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue DeprecatedInterface_foo(const djinni::swift::ParameterList* params) try {
    auto inst = NativeDeprecatedInterface::toCpp(params->getValue(0));
    auto ret = inst->foo();
    return ::djinni::swift::I32::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue DeprecatedInterface_bar(const djinni::swift::ParameterList* params) try {
    auto inst = NativeDeprecatedInterface::toCpp(params->getValue(0));
    auto ret = inst->bar();
    return ::djinni::swift::I32::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue DeprecatedInterfaceSwiftProxy::make(void* instance, djinni::swift::DispatchFunc dispatcher) {
    return {std::make_shared<DeprecatedInterfaceSwiftProxy>(instance, dispatcher)};
}
int32_t DeprecatedInterfaceSwiftProxy::foo() {
    djinni::swift::ParameterList params;
    return ::djinni::swift::I32::toCpp(callProtocol(0, &params));
}
int32_t DeprecatedInterfaceSwiftProxy::bar() {
    djinni::swift::ParameterList params;
    return ::djinni::swift::I32::toCpp(callProtocol(1, &params));
}

} // namespace djinni_generated
