// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_enum.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeDeprecatedEnum = djinni::swift::Enum<::testsuite::deprecated_enum>;

} // namespace djinni_generated
