// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedRecord.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue NativeDeprecatedRecord::fromCpp(const ::testsuite::DeprecatedRecord& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::I32::fromCpp(c.foo));
    ret->addValue(::djinni::swift::I32::fromCpp(c.bar));
    ret->addValue(::djinni::swift::I32::fromCpp(c.baz));
    return {ret};
}
::testsuite::DeprecatedRecord NativeDeprecatedRecord::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::DeprecatedRecord(::djinni::swift::I32::toCpp(p->getValue(0)), ::djinni::swift::I32::toCpp(p->getValue(1)), ::djinni::swift::I32::toCpp(p->getValue(2)));
}

} // namespace djinni_generated
