// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_record.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

struct NativeDeprecatedRecord {
    using CppType = ::testsuite::DeprecatedRecord;
    static djinni::swift::AnyValue fromCpp(const CppType& c);
    static CppType toCpp(const djinni::swift::AnyValue& s);
};

} // namespace djinni_generated
