// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedInterfaceWithMessage.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue DeprecatedInterfaceWithMessage_foo(const djinni::swift::ParameterList* params) try {
    auto inst = NativeDeprecatedInterfaceWithMessage::toCpp(params->getValue(0));
    auto ret = inst->foo();
    return ::djinni::swift::I32::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue DeprecatedInterfaceWithMessage_bar(const djinni::swift::ParameterList* params) try {
    auto inst = NativeDeprecatedInterfaceWithMessage::toCpp(params->getValue(0));
    auto ret = inst->bar();
    return ::djinni::swift::I32::fromCpp(ret);
}
catch (const std::exception& e) {
    return {djinni::swift::ErrorValue{ e.what(), std::current_exception()}};
}
djinni::swift::AnyValue DeprecatedInterfaceWithMessageSwiftProxy::make(void* instance, djinni::swift::DispatchFunc dispatcher) {
    return {std::make_shared<DeprecatedInterfaceWithMessageSwiftProxy>(instance, dispatcher)};
}
int32_t DeprecatedInterfaceWithMessageSwiftProxy::foo() {
    djinni::swift::ParameterList params;
    return ::djinni::swift::I32::toCpp(callProtocol(0, &params));
}
int32_t DeprecatedInterfaceWithMessageSwiftProxy::bar() {
    djinni::swift::ParameterList params;
    return ::djinni::swift::I32::toCpp(callProtocol(1, &params));
}

} // namespace djinni_generated
