// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_interface_with_message.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeDeprecatedInterfaceWithMessage = djinni::swift::Interface<::testsuite::DeprecatedInterfaceWithMessage>;

djinni::swift::AnyValue DeprecatedInterfaceWithMessage_foo(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue DeprecatedInterfaceWithMessage_bar(const djinni::swift::ParameterList* params);

class DeprecatedInterfaceWithMessageSwiftProxy: public ::testsuite::DeprecatedInterfaceWithMessage, public djinni::swift::ProtocolWrapper {
public:
    DeprecatedInterfaceWithMessageSwiftProxy(void* instance, djinni::swift::DispatchFunc dispatcher): ProtocolWrapper(instance, dispatcher) {}
    static djinni::swift::AnyValue make(void* instance, djinni::swift::DispatchFunc dispatcher);
    int32_t foo() override;
    int32_t bar() override;
};

} // namespace djinni_generated
