// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_interface.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeDeprecatedInterface = djinni::swift::Interface<::testsuite::DeprecatedInterface>;

djinni::swift::AnyValue DeprecatedInterface_foo(const djinni::swift::ParameterList* params);
djinni::swift::AnyValue DeprecatedInterface_bar(const djinni::swift::ParameterList* params);

class DeprecatedInterfaceSwiftProxy: public ::testsuite::DeprecatedInterface, public djinni::swift::ProtocolWrapper {
public:
    DeprecatedInterfaceSwiftProxy(void* instance, djinni::swift::DispatchFunc dispatcher): ProtocolWrapper(instance, dispatcher) {}
    static djinni::swift::AnyValue make(void* instance, djinni::swift::DispatchFunc dispatcher);
    int32_t foo() override;
    int32_t bar() override;
};

} // namespace djinni_generated
