// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedRecordWithMessage.hpp"  // my header

namespace djinni_generated {

djinni::swift::AnyValue NativeDeprecatedRecordWithMessage::fromCpp(const ::testsuite::DeprecatedRecordWithMessage& c) {
    auto ret = std::make_shared<djinni::swift::CompositeValue>();
    ret->addValue(::djinni::swift::I32::fromCpp(c.foo));
    ret->addValue(::djinni::swift::I32::fromCpp(c.bar));
    ret->addValue(::djinni::swift::I32::fromCpp(c.baz));
    return {ret};
}
::testsuite::DeprecatedRecordWithMessage NativeDeprecatedRecordWithMessage::toCpp(const djinni::swift::AnyValue& s) {
    auto p = std::get<djinni::swift::CompositeValuePtr>(s);
    return ::testsuite::DeprecatedRecordWithMessage(::djinni::swift::I32::toCpp(p->getValue(0)), ::djinni::swift::I32::toCpp(p->getValue(1)), ::djinni::swift::I32::toCpp(p->getValue(2)));
}

} // namespace djinni_generated
