// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#include "NativeDeprecatedEnumWithMessage.hpp"  // my header

namespace djinni_generated {


} // namespace djinni_generated
