// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#pragma once

#include "deprecated_enum_with_message.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

using NativeDeprecatedEnumWithMessage = djinni::swift::Enum<::testsuite::deprecated_enum_with_message>;

} // namespace djinni_generated
