// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import <Foundation/Foundation.h>


/** @deprecated This is a deprecation message */
__deprecated_msg("This is a deprecation message")
@interface DBDeprecatedInterfaceWithStatic : NSObject

/** @deprecated */
+ (int32_t)foo __deprecated;

/** @deprecated This is a deprecation message */
+ (int32_t)bar __deprecated_msg("This is a deprecation message");

@end
