// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import "DBDeprecatedRecordWithMessage.h"


@implementation DBDeprecatedRecordWithMessage

- (nonnull instancetype)initWithFoo:(int32_t)foo
                                bar:(int32_t)bar
                                baz:(int32_t)baz
{
    if (self = [super init]) {
        _foo = foo;
        _bar = bar;
        _baz = baz;
    }
    return self;
}

+ (nonnull instancetype)deprecatedRecordWithMessageWithFoo:(int32_t)foo
                                                       bar:(int32_t)bar
                                                       baz:(int32_t)baz
{
    return [[self alloc] initWithFoo:foo
                                 bar:bar
                                 baz:baz];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p foo:%@ bar:%@ baz:%@>", self.class, (void *)self, @(self.foo), @(self.bar), @(self.baz)];
}

#endif
@end
