// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#ifdef __cplusplus
#include "deprecated_interface.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DBDeprecatedInterface;

namespace djinni_generated {

class DeprecatedInterface
{
public:
    using CppType = std::shared_ptr<::testsuite::DeprecatedInterface>;
    using CppOptType = std::shared_ptr<::testsuite::DeprecatedInterface>;
    using ObjcType = id<DBDeprecatedInterface>;

    using Boxed = DeprecatedInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif // __cplusplus
