// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#ifdef __cplusplus
#import "DBDeprecatedInterfaceWithStatic+Private.h"
#import "DBDeprecatedInterfaceWithStatic.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DBDeprecatedInterfaceWithStatic ()

- (id)initWithCpp:(const std::shared_ptr<::testsuite::DeprecatedInterfaceWithStatic>&)cppRef;

@end

@implementation DBDeprecatedInterfaceWithStatic {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::testsuite::DeprecatedInterfaceWithStatic>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::testsuite::DeprecatedInterfaceWithStatic>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (int32_t)foo {
    try {
        auto objcpp_result_ = ::testsuite::DeprecatedInterfaceWithStatic::foo();
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (int32_t)bar {
    try {
        auto objcpp_result_ = ::testsuite::DeprecatedInterfaceWithStatic::bar();
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto DeprecatedInterfaceWithStatic::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto DeprecatedInterfaceWithStatic::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DBDeprecatedInterfaceWithStatic>(cpp);
}

} // namespace djinni_generated

@end
#endif // __cplusplus
