// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import <Foundation/Foundation.h>

/** @deprecated */
__deprecated
typedef NS_ENUM(NSInteger, DBDeprecatedEnum)
{
    DBDeprecatedEnumFoo = 0,
    /** @deprecated */
    DBDeprecatedEnumBar = 1,
    /** @deprecated This is a deprecation message */
    DBDeprecatedEnumBaz = 2,
};
