// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import <Foundation/Foundation.h>

/** @deprecated This is a deprecation message */
__deprecated_msg("This is a deprecation message")
typedef NS_ENUM(NSInteger, DBDeprecatedEnumWithMessage)
{
    DBDeprecatedEnumWithMessageFoo = 0,
    /** @deprecated */
    DBDeprecatedEnumWithMessageBar = 1,
    /** @deprecated This is a deprecation message */
    DBDeprecatedEnumWithMessageBaz = 2,
};
