// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#ifdef __cplusplus
#include "deprecated_enum.hpp"
#import "DJIMarshal+Private.h"

#endif // __cplusplus
