// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import <Foundation/Foundation.h>

/** @deprecated Deprecated constant */
extern int32_t const DBDeprecatedInterfaceBaz __deprecated_msg("Deprecated constant");

/** @deprecated */
__deprecated
@protocol DBDeprecatedInterface <NSObject>

/** @deprecated */
- (int32_t)foo __deprecated;

/** @deprecated This is a deprecation message */
- (int32_t)bar __deprecated_msg("This is a deprecation message");

@end
