// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#ifdef __cplusplus
#import "DBDeprecatedRecordWithMessage.h"
#include "deprecated_record_with_message.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBDeprecatedRecordWithMessage;

namespace djinni_generated {

struct DeprecatedRecordWithMessage
{
    using CppType = ::testsuite::DeprecatedRecordWithMessage;
    using ObjcType = DBDeprecatedRecordWithMessage*;

    using Boxed = DeprecatedRecordWithMessage;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif // __cplusplus
