// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import "DBDeprecatedInterfaceWithMessage.h"


int32_t const DBDeprecatedInterfaceWithMessageBaz = 0;
