// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecated.djinni

#import <Foundation/Foundation.h>

/** @deprecated */
__deprecated
@interface DBDeprecatedRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithFoo:(int32_t)foo
                                bar:(int32_t)bar
                                baz:(int32_t)baz NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)deprecatedRecordWithFoo:(int32_t)foo
                                            bar:(int32_t)bar
                                            baz:(int32_t)baz;

@property (nonatomic) int32_t foo;

/** @deprecated */
@property (nonatomic) int32_t bar __deprecated;

/** @deprecated This is a deprecation message */
@property (nonatomic) int32_t baz __deprecated_msg("This is a deprecation message");

@end
